# Generated by Django 2.2.13 on 2020-08-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last_updated'),
        ),
    ]
